#--------------------------------------------------------------------------------------#
#  Physics list                                                                        #
#--------------------------------------------------------------------------------------#
/gate/physics/addPhysicsList   emstandard_opt4

## Old method
#/gate/physics/addProcess PhotoElectric
#/gate/physics/processes/PhotoElectric/setModel StandardModel
#/gate/physics/addProcess Compton
#/gate/physics/processes/Compton/setModel StandardModel
#/gate/physics/addProcess RayleighScattering
#/gate/physics/processes/RayleighScattering/setModel LivermoreModel
#/gate/physics/addProcess ElectronIonisation
#/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
#/gate/physics/processes/ElectronIonisation/setModel StandardModel e+
#/gate/physics/addProcess Bremsstrahlung
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
#/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+
#/gate/physics/addProcess PositronAnnihilation
#/gate/physics/addProcess eMultipleScattering
#/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
#/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

# For ion sources
/gate/physics/addProcess RadioactiveDecay

/gate/physics/addAtomDeexcitation
#/process/em/fluo  false
#/process/em/auger false
#/process/em/pixe  false

/gate/physics/processList Enabled
/gate/physics/processList Initialized

# Production cuts - do not produce secondaries if below threshold
/gate/physics/setEMin 1 keV
/gate/physics/setEMax  1 GeV
/gate/physics/setDEDXBinning 220
/gate/physics/setLambdaBinning 220

# Cuts for particles
/gate/physics/Gamma/SetCutInRegion    world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/Positron/SetCutInRegion world 1 mm

/gate/physics/Gamma/SetCutInRegion    scatter_phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion scatter_phantom 0.1 mm
/gate/physics/Positron/SetCutInRegion scatter_phantom 0.1 mm

/gate/physics/Gamma/SetCutInRegion    LYSO 0.1 mm
/gate/physics/Electron/SetCutInRegion LYSO 0.1 mm
/gate/physics/Positron/SetCutInRegion LYSO 0.1 mm


