#--------------------------------------------------------------------------------------#
#  Visualization settings                                                              #
#--------------------------------------------------------------------------------------#
/vis/ogl/set/printMode vectored
/vis/ogl/printEPS              
/vis/open                               OGL
/vis/viewer/set/viewpointThetaPhi       0 0
/vis/drawVolume
/tracking/storeTrajectory               1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction             accumulate

/vis/viewer/zoom 1
/vis/viewer/panTo 60 -40 mm

